# render.yaml
services:
  - type: web
    name: fastapi-task-manager
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000
    envVars:
      - key: PORT
        value: 10000
